### ISSUE TITLE
Hide from external search engines?

### ISSUE THREAD

**Issue by bzmelotti** [enonic/app-sitemap-xml#18]
Hi guys, we are facing a problem related to SEO and we would like to do a change on sitemap app, but we would like to confirm with you first. We are using the sitemap and "SEO meta fields", but we have some folders (content type base:folder) that don't need to be indexed. The sitemap app is configured to exclude the content based on content type and it is not possible in our case because we have some base:folder contents that are important to SEO. We would like to add the option "Hide from external search engines?" on the sitemap app. That way, if someone is using the app "SEO meta fields", the contents that have the option "Hide from external search engines?" checked could be excluded from the sitemap xml. Does it make sense?

**Comment by rolfrb** [comment]
We have both the SEO app and the sitemap app installed on our sites. If I check "Hide from external search engines?" for a page in the SEO app, the page is removed from the /sitemap.xml file. But this doesn't work for you? 

If it doesn't, it might be a bug.
