### ISSUE TITLE
Limit entries to current site

### ISSUE THREAD

**Issue by nerdegutt** [enonic/app-sitemap-xml#7]
Thanks for a great plugin!

Would you consider a small improvement? On a multi site server you'll get a lot of entries like this one for content that isn't on the current site:

```
<url>
    <loc>/_/error/400?message=URI+out+of+scope</loc>
    <lastmod>2017-05-16</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.5</priority>
</url>
```

I suppose adding a query limit to the service would get rid of them?

`var query = '_path like "/content' + portalLib.getSite()._path + '/*"';
`

and use this in you query.

**Comment by Bellfalasch** [comment]
Surprised anyone uses this ;P Good idea, obviously. Should have been there from the start. Will look into it, unless you wanna send a pull request =)

**Comment by Bellfalasch** [comment]
I'm working on this now, simple fix. Will take care of a few other issues as well and release 1.1.0.

**Comment by nerdegutt** [comment]
Shit, I just made a pull req like you asked... Full crash with your fixes :D.

Just ignore the PR, then. But nice if you add the SEO thing, so I'm able to hide pages from sitemap.

**Comment by Bellfalasch** [comment]
Woops, my bad. I looked at the code after your suggestions and got all carried away and changed everything ... sorry. I'll add the SEO-things for 1.1.0 too. Thx! Just some local testing first. Stay tuned!

**Comment by nerdegutt** [comment]
Follow the flow and fuel the passion! Looking forward to the changes...

**Comment by Bellfalasch** [comment]
Using the all new and powerful (blazingly fast) query filter function for this. Requires XP to be 6.10. Hope that works for you.

1.1.0 is ready. Please pull and build locally and make sure I didn't broke anything. Works very fine on my three test sites locally.

**Comment by Bellfalasch** [comment]
Released on market. Enjoy!
