### ISSUE TITLE
Respect SEO plugin robot blocking

### ISSUE THREAD

**Issue by nerdegutt** [enonic/app-sitemap-xml#8]
Another feature suggestion: 

The superduper «official» Enonic [SEO metadata plugin](https://github.com/enonic/app-metafields) has a setting to block robots for specific pages. This probably means you don't want to have it in your sitemap either.

It will produce this field in your content:

```
"x": {
    "com-enonic-app-metafields": {
      "meta-data": {
        "blockRobots": true
      }
    }
  }

```

To also ignore these in sitemap.xml, it would be great if you would consider add

`x.com-enonic-app-metafields.meta-data.blockRobots != 'true'`

to the query.

It will simply be ignored for content not having this content.

**Comment by Bellfalasch** [comment]
Thanks! Ships in 1.1.0
