### ISSUE TITLE
Max Included Items limits

### ISSUE THREAD

**Issue by rymsha** [enonic/app-sitemap-xml#84]
`Max Included Items` should be limited to accept values from 1 to 50000. The default value is 10000.

When `Max Included Items` is set to 1 - 10000 sitemap application should do a node query with respective `size` (1 - 10000), and fetch/convert every node returned.

When set to  any other value (10001 - 50000) sitemap application should do a node query with `size = -1`, but abort fetch/convert as soon as `Max Included Items` are processed.

**Comment by ComLock** [comment]
> Max Included Items should be limited to accept values from 1 to 50000.
Already correct
![Screenshot 2024-03-07 at 14 35 19](https://github.com/enonic/app-sitemap-xml/assets/118847/f0217990-55d5-4fc7-a413-72889e8455f2)

> The default value is 10000.
Been like that for a while

![Screenshot 2024-03-07 at 14 36 23](https://github.com/enonic/app-sitemap-xml/assets/118847/69f1d88c-a225-490c-ae7a-361f28bb0ab7)

**Comment by ComLock** [comment]
> I think it is possible to use https://developer.enonic.com/docs/xp/stable/cms/schemas/input-types/long
with min/max provided
Yes, but content studio get console error and stops working when historical string value exists
